export const toursList = [
  {
    id: 1,
    title: "Umayyad Mosque",
    duration: "4 - 7 hours",
    rating: 4.5,
    reviews: "6,202",
    priceFrom: 35.44,
    image: "/tours/1.jpg",
  },
  {
    id: 2,
    title: "King's Daughter's Bed",
    duration: "7 hours",
    rating: 4.5,
    reviews: "2,425",
    priceFrom: 52.96,
    image: "/tours/2.jpg",
  },
  {
    id: 3,
    title: "Maktab Anbar",
    duration: "5 hours",
    rating: 4,
    reviews: "1,002",
    priceFrom: 34.21,
    image: "/tours/3.jpg",
  },
  {
    id: 4,
    title: "Al-Hisn Castle",
    duration: "6 hours",
    rating: 3.5,
    reviews: "87",
    priceFrom: 28.98,
    image: "/tours/4.jpg",
  },
  {
    id: 5,
    title: "Mediterranean Sea In Latakia",
    duration: "5 - 8 hours",
    rating: 4.5,
    reviews: "14,548",
    priceFrom: 31.98,
    image: "/tours/5.jpg",
  },
  {
    id: 6,
    title: "Roman Theatre At Bosra",
    duration: "4 hours",
    rating: 5,
    reviews: "5,580",
    priceFrom: 25.98,
    image: "/tours/6.jpg",
  },
  {
    id: 7,
    title: "Azm Palace",
    duration: "7 hours",
    rating: 4.5,
    reviews: "785",
    priceFrom: 53.32,
    image: "/tours/7.jpg",
  },
  {
    id: 8,
    title: "Hama Water Wheels",
    duration: "7 hours",
    rating: 4.5,
    reviews: "8,412",
    priceFrom: 41.96,
    image: "/tours/8.jpg",
  },
  {
    id: 9,
    title: "Ugarit",
    duration: "10 - 14 hours",
    rating: 5,
    reviews: "21,541",
    priceFrom: 78.9,
    image: "/tours/9.jpg",
  },
  {
    id: 10,
    title: "Qasioun Mountain",
    duration: "4 - 6 hours",
    rating: 4,
    reviews: "8,412",
    priceFrom: 35.98,
    image: "/tours/10.jpg",
  },
  {
    id: 11,
    title: "Ibn Wardan Palace",
    duration: "4 - 6 hours",
    rating: 3,
    reviews: "5,751",
    priceFrom: 38.26,
    image: "/tours/11.jpg",
  },
  {
    id: 12,
    title: "AL-Sheikh Mountain",
    duration: "4 - 7 hours",
    rating: 4.5,
    reviews: "6,301",
    priceFrom: 41.44,
    image: "/tours/12.jpg",
  },
  {
    id: 13,
    title: "Barada River",
    duration: "3 - 4 hours",
    rating: 4.8,
    reviews: "4,412",
    priceFrom: 31.44,
    image: "/tours/13.jpg",
  },
  {
    id: 14,
    title: "Happy Land Park",
    duration: "6 hours",
    rating: 5,
    reviews: "925",
    priceFrom: 92.27,
    image: "/tours/14.jpg",
  },
  {
    id: 15,
    title: "Ghouta of Damascus",
    duration: "5 hours",
    rating: 4,
    reviews: "7,772",
    priceFrom: 44.21,
    image: "/tours/15.jpg",
  },
  {
    id: 16,
    title: "Tabariya Lake",
    duration: "4 - 6 hours",
    rating: 4.6,
    reviews: "15,879",
    priceFrom: 44.98,
    image: "/tours/16.jpg",
  },
  {
    id: 17,
    title: "Palmyra Ruins",
    duration: "1 - 6 hours",
    rating: 4.8,
    reviews: "6,245",
    priceFrom: 21.98,
    image: "/tours/17.jpg",
  },
  {
    id: 18,
    title: "Aleppo Castle",
    duration: "4 hours",
    rating: 4.1,
    reviews: "12,102",
    priceFrom: 18.21,
    image: "/tours/18.jpg",
  },
  {
    id: 19,
    title: "Arwad Island",
    duration: "5 hours",
    rating: 4.4,
    reviews: "1,233",
    priceFrom: 48.0,
    image: "/tours/19.jpg",
  },
  {
    id: 20,
    title: "Umayyad Square",
    duration: "17 hours",
    rating: 5,
    reviews: "6,870",
    priceFrom: 161.12,
    image: "/tours/20.jpg",
  },
  {
    id: 21,
    title: "The National Museum",
    duration: "4 - 5 hours",
    rating: 3.9,
    reviews: "32",
    priceFrom: 78.9,
    image: "/tours/21.jpg",
  },
  {
    id: 22,
    title: "Al-Hamidiyai Souq",
    duration: "6 hours",
    rating: 4.1,
    reviews: "2,987",
    priceFrom: 31.98,
    image: "/tours/22.jpg",
  },
  {
    id: 23,
    title: "Euphrates Dam",
    duration: "4 hours",
    rating: 4.5,
    reviews: "7,751",
    priceFrom: 321.26,
    image: "/tours/23.jpg",
  },
  {
    id: 24,
    title: "Afamia",
    duration: "7 hours",
    rating: 4.6,
    reviews: "17,301",
    priceFrom: 58.44,
    image: "/tours/24.jpg",
  },
];

export const languages = [
  {
    id: 1,
    value: "English (US)",
  },
  {
    id: 2,
    value: "English (UK)",
  },
  {
    id: 3,
    value: "Arabic (Gulf)",
  },
  {
    id: 4,
    value: "Arabic (Egypt)",
  },
  {
    id: 5,
    value: "Arabic (Iraq)",
  },
  {
    id: 6,
    value: "Deutsch (Deutschland)",
  },
  {
    id: 7,
    value: "Deutsch (Schwiz)",
  },
  {
    id: 8,
    value: "Espanol",
  },
  {
    id: 9,
    value: "Portugues",
  },
  {
    id: 10,
    value: "Francais",
  },
  {
    id: 11,
    value: "Turkish",
  },
  {
    id: 12,
    value: "Persian",
  },
  {
    id: 13,
    value: "Kurdi",
  },
  {
    id: 14,
    value: "Chinees",
  },
];

export const currencies = [
  {
    id: 1,
    value: "UAE (Dirham)",
  },
  {
    id: 2,
    value: "Euro",
  },
  {
    id: 3,
    value: "US Dollar",
  },
  {
    id: 4,
    value: "Swiss Franc (CHF)",
  },
  {
    id: 5,
    value: "British Pound",
  },
  {
    id: 6,
    value: "Egyption Pound",
  },
  {
    id: 7,
    value: "Iraqi Dinar",
  },
  {
    id: 8,
    value: "Turkish Lira",
  },
  {
    id: 9,
    value: "Hong Kong Dollar",
  },
  {
    id: 10,
    value: "Canadian Dollar",
  },
];
